//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFARTHA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKKO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EKKO()
        {
            this.DOCUMENTOes = new HashSet<DOCUMENTO>();
        }
    
        public string EBELN { get; set; }
        public string BUKRS { get; set; }
        public string BSART { get; set; }
        public string LIFNR { get; set; }
        public string RETTP { get; set; }
        public Nullable<decimal> RETPC { get; set; }
        public string DPTYP { get; set; }
        public Nullable<decimal> DPPCT { get; set; }
        public Nullable<decimal> DPAMT { get; set; }
        public string ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTOes { get; set; }
    }
}
